i2c:
  enabled: true
  path: modules.i2c.I2C
  config:
    port: 1 # port 1 is used for i2c on the raspberry pi newer than October 2012, port 0 is used for older models
  dependencies:
    unix:
      - python3-smbus
    python:
      - adafruit-circuitpython-servokit