logwrapper:
  enabled: true # Highly recommended to enable this module
  path: modules.logwrapper.LogWrapper
  config:
    filename: app.log
    print: true
  dependencies:
    python:
      - pypubsub
