servos:
  enabled: true
  path: "modules.actuators.servo.Servo" # Include class name here
  instances:
    # - name: "leg_l_hip"
    #   id: 0
    #   pin: 9
    #   range: [0, 180]
    #   start: 45
    # - name: "leg_l_knee"
    #   id: 1
    #   pin: 10
    #   range: [0, 180]
    #   start: 75
    # - name: "leg_l_ankle"
    #   id: 2
    #   pin: 11
    #   range: [5, 165]
    #   start: 80
    # - name: "leg_r_hip"
    #   id: 3
    #   pin: 6
    #   range: [0, 180]
    #   start: 135
    # - name: "leg_r_knee"
    #   id: 4
    #   pin: 7
    #   range: [0, 180]
    #   start: 105
    # - name: "leg_r_ankle"
    #   id: 5
    #   pin: 8
    #   range: [20, 180]
    #   start: 100
    - name: "tilt"
      id: 6
      pin: 2
      range: [60, 120]
      start: 50
    - name: "pan"
      id: 7
      pin: 3
      range: [30, 150]
      start: 50
  dependencies:
    python:
      - pypubsub
      - pigpio