speechinput:
  enabled: false
  path: modules.audio.speechinput.SpeechInput
  config:
    device_name: lp
    start_on_boot: false
  dependencies:
    unix:
      - flac
      - python3-pyaudio
      # - matplotlib
      # - scipy
      - ladspa-sdk
    python:
      - pypubsub
      - SpeechRecognition
      # - adafruit-python-shell
      # - libportaudio0
      # - libportaudio2
      # - libportaudiocpp0
      # - portaudio19-dev
    additional:
      - installers/install-mics.sh
      - installers/install-speech-recognition.sh