telegram:
  enabled: false
  path: modules.network.telegrambot.TelegramBot
  config:
    user_whitelist: []
  dependencies:
    python:
      - pypubsub
      - python-telegram-bot
    additional:
      - https://core.telegram.org/bots/tutorial#obtain-your-bot-token